/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EduPortalAdminRouteImport } from './routes/edu-portal-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EduPortalAdminIndexRouteImport } from './routes/edu-portal-admin.index'
import { Route as SlidesSplatRouteImport } from './routes/slides.$'
import { Route as MarkdownSplatRouteImport } from './routes/markdown.$'
import { Route as FinderSplatRouteImport } from './routes/finder.$'
import { Route as EduPortalAdminVideosRouteImport } from './routes/edu-portal-admin.videos'
import { Route as EduPortalAdminVideoOrderRouteImport } from './routes/edu-portal-admin.video-order'
import { Route as EduPortalAdminRoleCategoriesRouteImport } from './routes/edu-portal-admin.role-categories'
import { Route as EduPortalAdminDashboardRouteImport } from './routes/edu-portal-admin.dashboard'
import { Route as EduPortalAdminCourseCategoriesRouteImport } from './routes/edu-portal-admin.course-categories'
import { Route as EduPortalAdminVideosIndexRouteImport } from './routes/edu-portal-admin.videos.index'
import { Route as EduPortalAdminVideosNewRouteImport } from './routes/edu-portal-admin.videos.new'
import { Route as EduPortalAdminVideosIdEditRouteImport } from './routes/edu-portal-admin.videos.$id.edit'

const EduPortalAdminRoute = EduPortalAdminRouteImport.update({
  id: '/edu-portal-admin',
  path: '/edu-portal-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EduPortalAdminIndexRoute = EduPortalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EduPortalAdminRoute,
} as any)
const SlidesSplatRoute = SlidesSplatRouteImport.update({
  id: '/slides/$',
  path: '/slides/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarkdownSplatRoute = MarkdownSplatRouteImport.update({
  id: '/markdown/$',
  path: '/markdown/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderSplatRoute = FinderSplatRouteImport.update({
  id: '/finder/$',
  path: '/finder/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EduPortalAdminVideosRoute = EduPortalAdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => EduPortalAdminRoute,
} as any)
const EduPortalAdminVideoOrderRoute =
  EduPortalAdminVideoOrderRouteImport.update({
    id: '/video-order',
    path: '/video-order',
    getParentRoute: () => EduPortalAdminRoute,
  } as any)
const EduPortalAdminRoleCategoriesRoute =
  EduPortalAdminRoleCategoriesRouteImport.update({
    id: '/role-categories',
    path: '/role-categories',
    getParentRoute: () => EduPortalAdminRoute,
  } as any)
const EduPortalAdminDashboardRoute = EduPortalAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EduPortalAdminRoute,
} as any)
const EduPortalAdminCourseCategoriesRoute =
  EduPortalAdminCourseCategoriesRouteImport.update({
    id: '/course-categories',
    path: '/course-categories',
    getParentRoute: () => EduPortalAdminRoute,
  } as any)
const EduPortalAdminVideosIndexRoute =
  EduPortalAdminVideosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EduPortalAdminVideosRoute,
  } as any)
const EduPortalAdminVideosNewRoute = EduPortalAdminVideosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EduPortalAdminVideosRoute,
} as any)
const EduPortalAdminVideosIdEditRoute =
  EduPortalAdminVideosIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => EduPortalAdminVideosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/edu-portal-admin': typeof EduPortalAdminRouteWithChildren
  '/edu-portal-admin/course-categories': typeof EduPortalAdminCourseCategoriesRoute
  '/edu-portal-admin/dashboard': typeof EduPortalAdminDashboardRoute
  '/edu-portal-admin/role-categories': typeof EduPortalAdminRoleCategoriesRoute
  '/edu-portal-admin/video-order': typeof EduPortalAdminVideoOrderRoute
  '/edu-portal-admin/videos': typeof EduPortalAdminVideosRouteWithChildren
  '/finder/$': typeof FinderSplatRoute
  '/markdown/$': typeof MarkdownSplatRoute
  '/slides/$': typeof SlidesSplatRoute
  '/edu-portal-admin/': typeof EduPortalAdminIndexRoute
  '/edu-portal-admin/videos/new': typeof EduPortalAdminVideosNewRoute
  '/edu-portal-admin/videos/': typeof EduPortalAdminVideosIndexRoute
  '/edu-portal-admin/videos/$id/edit': typeof EduPortalAdminVideosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/edu-portal-admin/course-categories': typeof EduPortalAdminCourseCategoriesRoute
  '/edu-portal-admin/dashboard': typeof EduPortalAdminDashboardRoute
  '/edu-portal-admin/role-categories': typeof EduPortalAdminRoleCategoriesRoute
  '/edu-portal-admin/video-order': typeof EduPortalAdminVideoOrderRoute
  '/finder/$': typeof FinderSplatRoute
  '/markdown/$': typeof MarkdownSplatRoute
  '/slides/$': typeof SlidesSplatRoute
  '/edu-portal-admin': typeof EduPortalAdminIndexRoute
  '/edu-portal-admin/videos/new': typeof EduPortalAdminVideosNewRoute
  '/edu-portal-admin/videos': typeof EduPortalAdminVideosIndexRoute
  '/edu-portal-admin/videos/$id/edit': typeof EduPortalAdminVideosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/edu-portal-admin': typeof EduPortalAdminRouteWithChildren
  '/edu-portal-admin/course-categories': typeof EduPortalAdminCourseCategoriesRoute
  '/edu-portal-admin/dashboard': typeof EduPortalAdminDashboardRoute
  '/edu-portal-admin/role-categories': typeof EduPortalAdminRoleCategoriesRoute
  '/edu-portal-admin/video-order': typeof EduPortalAdminVideoOrderRoute
  '/edu-portal-admin/videos': typeof EduPortalAdminVideosRouteWithChildren
  '/finder/$': typeof FinderSplatRoute
  '/markdown/$': typeof MarkdownSplatRoute
  '/slides/$': typeof SlidesSplatRoute
  '/edu-portal-admin/': typeof EduPortalAdminIndexRoute
  '/edu-portal-admin/videos/new': typeof EduPortalAdminVideosNewRoute
  '/edu-portal-admin/videos/': typeof EduPortalAdminVideosIndexRoute
  '/edu-portal-admin/videos/$id/edit': typeof EduPortalAdminVideosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/edu-portal-admin'
    | '/edu-portal-admin/course-categories'
    | '/edu-portal-admin/dashboard'
    | '/edu-portal-admin/role-categories'
    | '/edu-portal-admin/video-order'
    | '/edu-portal-admin/videos'
    | '/finder/$'
    | '/markdown/$'
    | '/slides/$'
    | '/edu-portal-admin/'
    | '/edu-portal-admin/videos/new'
    | '/edu-portal-admin/videos/'
    | '/edu-portal-admin/videos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/edu-portal-admin/course-categories'
    | '/edu-portal-admin/dashboard'
    | '/edu-portal-admin/role-categories'
    | '/edu-portal-admin/video-order'
    | '/finder/$'
    | '/markdown/$'
    | '/slides/$'
    | '/edu-portal-admin'
    | '/edu-portal-admin/videos/new'
    | '/edu-portal-admin/videos'
    | '/edu-portal-admin/videos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/edu-portal-admin'
    | '/edu-portal-admin/course-categories'
    | '/edu-portal-admin/dashboard'
    | '/edu-portal-admin/role-categories'
    | '/edu-portal-admin/video-order'
    | '/edu-portal-admin/videos'
    | '/finder/$'
    | '/markdown/$'
    | '/slides/$'
    | '/edu-portal-admin/'
    | '/edu-portal-admin/videos/new'
    | '/edu-portal-admin/videos/'
    | '/edu-portal-admin/videos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EduPortalAdminRoute: typeof EduPortalAdminRouteWithChildren
  FinderSplatRoute: typeof FinderSplatRoute
  MarkdownSplatRoute: typeof MarkdownSplatRoute
  SlidesSplatRoute: typeof SlidesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/edu-portal-admin': {
      id: '/edu-portal-admin'
      path: '/edu-portal-admin'
      fullPath: '/edu-portal-admin'
      preLoaderRoute: typeof EduPortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-portal-admin/': {
      id: '/edu-portal-admin/'
      path: '/'
      fullPath: '/edu-portal-admin/'
      preLoaderRoute: typeof EduPortalAdminIndexRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/slides/$': {
      id: '/slides/$'
      path: '/slides/$'
      fullPath: '/slides/$'
      preLoaderRoute: typeof SlidesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markdown/$': {
      id: '/markdown/$'
      path: '/markdown/$'
      fullPath: '/markdown/$'
      preLoaderRoute: typeof MarkdownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder/$': {
      id: '/finder/$'
      path: '/finder/$'
      fullPath: '/finder/$'
      preLoaderRoute: typeof FinderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-portal-admin/videos': {
      id: '/edu-portal-admin/videos'
      path: '/videos'
      fullPath: '/edu-portal-admin/videos'
      preLoaderRoute: typeof EduPortalAdminVideosRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/video-order': {
      id: '/edu-portal-admin/video-order'
      path: '/video-order'
      fullPath: '/edu-portal-admin/video-order'
      preLoaderRoute: typeof EduPortalAdminVideoOrderRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/role-categories': {
      id: '/edu-portal-admin/role-categories'
      path: '/role-categories'
      fullPath: '/edu-portal-admin/role-categories'
      preLoaderRoute: typeof EduPortalAdminRoleCategoriesRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/dashboard': {
      id: '/edu-portal-admin/dashboard'
      path: '/dashboard'
      fullPath: '/edu-portal-admin/dashboard'
      preLoaderRoute: typeof EduPortalAdminDashboardRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/course-categories': {
      id: '/edu-portal-admin/course-categories'
      path: '/course-categories'
      fullPath: '/edu-portal-admin/course-categories'
      preLoaderRoute: typeof EduPortalAdminCourseCategoriesRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/videos/': {
      id: '/edu-portal-admin/videos/'
      path: '/'
      fullPath: '/edu-portal-admin/videos/'
      preLoaderRoute: typeof EduPortalAdminVideosIndexRouteImport
      parentRoute: typeof EduPortalAdminVideosRoute
    }
    '/edu-portal-admin/videos/new': {
      id: '/edu-portal-admin/videos/new'
      path: '/new'
      fullPath: '/edu-portal-admin/videos/new'
      preLoaderRoute: typeof EduPortalAdminVideosNewRouteImport
      parentRoute: typeof EduPortalAdminVideosRoute
    }
    '/edu-portal-admin/videos/$id/edit': {
      id: '/edu-portal-admin/videos/$id/edit'
      path: '/$id/edit'
      fullPath: '/edu-portal-admin/videos/$id/edit'
      preLoaderRoute: typeof EduPortalAdminVideosIdEditRouteImport
      parentRoute: typeof EduPortalAdminVideosRoute
    }
  }
}

interface EduPortalAdminVideosRouteChildren {
  EduPortalAdminVideosNewRoute: typeof EduPortalAdminVideosNewRoute
  EduPortalAdminVideosIndexRoute: typeof EduPortalAdminVideosIndexRoute
  EduPortalAdminVideosIdEditRoute: typeof EduPortalAdminVideosIdEditRoute
}

const EduPortalAdminVideosRouteChildren: EduPortalAdminVideosRouteChildren = {
  EduPortalAdminVideosNewRoute: EduPortalAdminVideosNewRoute,
  EduPortalAdminVideosIndexRoute: EduPortalAdminVideosIndexRoute,
  EduPortalAdminVideosIdEditRoute: EduPortalAdminVideosIdEditRoute,
}

const EduPortalAdminVideosRouteWithChildren =
  EduPortalAdminVideosRoute._addFileChildren(EduPortalAdminVideosRouteChildren)

interface EduPortalAdminRouteChildren {
  EduPortalAdminCourseCategoriesRoute: typeof EduPortalAdminCourseCategoriesRoute
  EduPortalAdminDashboardRoute: typeof EduPortalAdminDashboardRoute
  EduPortalAdminRoleCategoriesRoute: typeof EduPortalAdminRoleCategoriesRoute
  EduPortalAdminVideoOrderRoute: typeof EduPortalAdminVideoOrderRoute
  EduPortalAdminVideosRoute: typeof EduPortalAdminVideosRouteWithChildren
  EduPortalAdminIndexRoute: typeof EduPortalAdminIndexRoute
}

const EduPortalAdminRouteChildren: EduPortalAdminRouteChildren = {
  EduPortalAdminCourseCategoriesRoute: EduPortalAdminCourseCategoriesRoute,
  EduPortalAdminDashboardRoute: EduPortalAdminDashboardRoute,
  EduPortalAdminRoleCategoriesRoute: EduPortalAdminRoleCategoriesRoute,
  EduPortalAdminVideoOrderRoute: EduPortalAdminVideoOrderRoute,
  EduPortalAdminVideosRoute: EduPortalAdminVideosRouteWithChildren,
  EduPortalAdminIndexRoute: EduPortalAdminIndexRoute,
}

const EduPortalAdminRouteWithChildren = EduPortalAdminRoute._addFileChildren(
  EduPortalAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EduPortalAdminRoute: EduPortalAdminRouteWithChildren,
  FinderSplatRoute: FinderSplatRoute,
  MarkdownSplatRoute: MarkdownSplatRoute,
  SlidesSplatRoute: SlidesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
