/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WireframesRouteImport } from './routes/wireframes'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as SoundSettingsRouteImport } from './routes/sound-settings'
import { Route as SidebarGalleryRouteImport } from './routes/sidebar-gallery'
import { Route as KeyboardRouteImport } from './routes/keyboard'
import { Route as InspectorRouteImport } from './routes/inspector'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as EduPortalAdminRouteImport } from './routes/edu-portal-admin'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CompositionsRouteImport } from './routes/compositions'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GenresIndexRouteImport } from './routes/genres.index'
import { Route as EduPortalAdminIndexRouteImport } from './routes/edu-portal-admin.index'
import { Route as MarkdownSplatRouteImport } from './routes/markdown.$'
import { Route as GenresShopRouteImport } from './routes/genres.shop'
import { Route as GenresSettingsRouteImport } from './routes/genres.settings'
import { Route as GenresInboxRouteImport } from './routes/genres.inbox'
import { Route as GenresFeedRouteImport } from './routes/genres.feed'
import { Route as GenresEditorRouteImport } from './routes/genres.editor'
import { Route as GenresCrmRouteImport } from './routes/genres.crm'
import { Route as GenresChatRouteImport } from './routes/genres.chat'
import { Route as GenresBoardRouteImport } from './routes/genres.board'
import { Route as GenresAnalyticsRouteImport } from './routes/genres.analytics'
import { Route as FinderSplatRouteImport } from './routes/finder.$'
import { Route as EduPortalAdminVideosRouteImport } from './routes/edu-portal-admin.videos'
import { Route as EduPortalAdminVideoOrderRouteImport } from './routes/edu-portal-admin.video-order'
import { Route as EduPortalAdminRoleCategoriesRouteImport } from './routes/edu-portal-admin.role-categories'
import { Route as EduPortalAdminDashboardRouteImport } from './routes/edu-portal-admin.dashboard'
import { Route as EduPortalAdminCourseCategoriesRouteImport } from './routes/edu-portal-admin.course-categories'
import { Route as DevtoolsFinderSpecRouteImport } from './routes/devtools.finder-spec'
import { Route as EduPortalAdminVideosIndexRouteImport } from './routes/edu-portal-admin.videos.index'
import { Route as MFinderSplatRouteImport } from './routes/m.finder.$'
import { Route as EduPortalAdminVideosNewRouteImport } from './routes/edu-portal-admin.videos.new'
import { Route as EduPortalAdminVideosIdEditRouteImport } from './routes/edu-portal-admin.videos.$id.edit'

const WireframesRoute = WireframesRouteImport.update({
  id: '/wireframes',
  path: '/wireframes',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundSettingsRoute = SoundSettingsRouteImport.update({
  id: '/sound-settings',
  path: '/sound-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarGalleryRoute = SidebarGalleryRouteImport.update({
  id: '/sidebar-gallery',
  path: '/sidebar-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const KeyboardRoute = KeyboardRouteImport.update({
  id: '/keyboard',
  path: '/keyboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectorRoute = InspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const EduPortalAdminRoute = EduPortalAdminRouteImport.update({
  id: '/edu-portal-admin',
  path: '/edu-portal-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CompositionsRoute = CompositionsRouteImport.update({
  id: '/compositions',
  path: '/compositions',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GenresRoute,
} as any)
const EduPortalAdminIndexRoute = EduPortalAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EduPortalAdminRoute,
} as any)
const MarkdownSplatRoute = MarkdownSplatRouteImport.update({
  id: '/markdown/$',
  path: '/markdown/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresShopRoute = GenresShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => GenresRoute,
} as any)
const GenresSettingsRoute = GenresSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => GenresRoute,
} as any)
const GenresInboxRoute = GenresInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => GenresRoute,
} as any)
const GenresFeedRoute = GenresFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => GenresRoute,
} as any)
const GenresEditorRoute = GenresEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => GenresRoute,
} as any)
const GenresCrmRoute = GenresCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => GenresRoute,
} as any)
const GenresChatRoute = GenresChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => GenresRoute,
} as any)
const GenresBoardRoute = GenresBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => GenresRoute,
} as any)
const GenresAnalyticsRoute = GenresAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => GenresRoute,
} as any)
const FinderSplatRoute = FinderSplatRouteImport.update({
  id: '/finder/$',
  path: '/finder/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EduPortalAdminVideosRoute = EduPortalAdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => EduPortalAdminRoute,
} as any)
const EduPortalAdminVideoOrderRoute =
  EduPortalAdminVideoOrderRouteImport.update({
    id: '/video-order',
    path: '/video-order',
    getParentRoute: () => EduPortalAdminRoute,
  } as any)
const EduPortalAdminRoleCategoriesRoute =
  EduPortalAdminRoleCategoriesRouteImport.update({
    id: '/role-categories',
    path: '/role-categories',
    getParentRoute: () => EduPortalAdminRoute,
  } as any)
const EduPortalAdminDashboardRoute = EduPortalAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => EduPortalAdminRoute,
} as any)
const EduPortalAdminCourseCategoriesRoute =
  EduPortalAdminCourseCategoriesRouteImport.update({
    id: '/course-categories',
    path: '/course-categories',
    getParentRoute: () => EduPortalAdminRoute,
  } as any)
const DevtoolsFinderSpecRoute = DevtoolsFinderSpecRouteImport.update({
  id: '/devtools/finder-spec',
  path: '/devtools/finder-spec',
  getParentRoute: () => rootRouteImport,
} as any)
const EduPortalAdminVideosIndexRoute =
  EduPortalAdminVideosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => EduPortalAdminVideosRoute,
  } as any)
const MFinderSplatRoute = MFinderSplatRouteImport.update({
  id: '/m/finder/$',
  path: '/m/finder/$',
  getParentRoute: () => rootRouteImport,
} as any)
const EduPortalAdminVideosNewRoute = EduPortalAdminVideosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EduPortalAdminVideosRoute,
} as any)
const EduPortalAdminVideosIdEditRoute =
  EduPortalAdminVideosIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => EduPortalAdminVideosRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/compositions': typeof CompositionsRoute
  '/content': typeof ContentRoute
  '/edu-portal-admin': typeof EduPortalAdminRouteWithChildren
  '/genres': typeof GenresRouteWithChildren
  '/inspector': typeof InspectorRoute
  '/keyboard': typeof KeyboardRoute
  '/sidebar-gallery': typeof SidebarGalleryRoute
  '/sound-settings': typeof SoundSettingsRoute
  '/tokens': typeof TokensRoute
  '/wireframes': typeof WireframesRoute
  '/devtools/finder-spec': typeof DevtoolsFinderSpecRoute
  '/edu-portal-admin/course-categories': typeof EduPortalAdminCourseCategoriesRoute
  '/edu-portal-admin/dashboard': typeof EduPortalAdminDashboardRoute
  '/edu-portal-admin/role-categories': typeof EduPortalAdminRoleCategoriesRoute
  '/edu-portal-admin/video-order': typeof EduPortalAdminVideoOrderRoute
  '/edu-portal-admin/videos': typeof EduPortalAdminVideosRouteWithChildren
  '/finder/$': typeof FinderSplatRoute
  '/genres/analytics': typeof GenresAnalyticsRoute
  '/genres/board': typeof GenresBoardRoute
  '/genres/chat': typeof GenresChatRoute
  '/genres/crm': typeof GenresCrmRoute
  '/genres/editor': typeof GenresEditorRoute
  '/genres/feed': typeof GenresFeedRoute
  '/genres/inbox': typeof GenresInboxRoute
  '/genres/settings': typeof GenresSettingsRoute
  '/genres/shop': typeof GenresShopRoute
  '/markdown/$': typeof MarkdownSplatRoute
  '/edu-portal-admin/': typeof EduPortalAdminIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/edu-portal-admin/videos/new': typeof EduPortalAdminVideosNewRoute
  '/m/finder/$': typeof MFinderSplatRoute
  '/edu-portal-admin/videos/': typeof EduPortalAdminVideosIndexRoute
  '/edu-portal-admin/videos/$id/edit': typeof EduPortalAdminVideosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/compositions': typeof CompositionsRoute
  '/content': typeof ContentRoute
  '/inspector': typeof InspectorRoute
  '/keyboard': typeof KeyboardRoute
  '/sidebar-gallery': typeof SidebarGalleryRoute
  '/sound-settings': typeof SoundSettingsRoute
  '/tokens': typeof TokensRoute
  '/wireframes': typeof WireframesRoute
  '/devtools/finder-spec': typeof DevtoolsFinderSpecRoute
  '/edu-portal-admin/course-categories': typeof EduPortalAdminCourseCategoriesRoute
  '/edu-portal-admin/dashboard': typeof EduPortalAdminDashboardRoute
  '/edu-portal-admin/role-categories': typeof EduPortalAdminRoleCategoriesRoute
  '/edu-portal-admin/video-order': typeof EduPortalAdminVideoOrderRoute
  '/finder/$': typeof FinderSplatRoute
  '/genres/analytics': typeof GenresAnalyticsRoute
  '/genres/board': typeof GenresBoardRoute
  '/genres/chat': typeof GenresChatRoute
  '/genres/crm': typeof GenresCrmRoute
  '/genres/editor': typeof GenresEditorRoute
  '/genres/feed': typeof GenresFeedRoute
  '/genres/inbox': typeof GenresInboxRoute
  '/genres/settings': typeof GenresSettingsRoute
  '/genres/shop': typeof GenresShopRoute
  '/markdown/$': typeof MarkdownSplatRoute
  '/edu-portal-admin': typeof EduPortalAdminIndexRoute
  '/genres': typeof GenresIndexRoute
  '/edu-portal-admin/videos/new': typeof EduPortalAdminVideosNewRoute
  '/m/finder/$': typeof MFinderSplatRoute
  '/edu-portal-admin/videos': typeof EduPortalAdminVideosIndexRoute
  '/edu-portal-admin/videos/$id/edit': typeof EduPortalAdminVideosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canvas': typeof CanvasRoute
  '/compositions': typeof CompositionsRoute
  '/content': typeof ContentRoute
  '/edu-portal-admin': typeof EduPortalAdminRouteWithChildren
  '/genres': typeof GenresRouteWithChildren
  '/inspector': typeof InspectorRoute
  '/keyboard': typeof KeyboardRoute
  '/sidebar-gallery': typeof SidebarGalleryRoute
  '/sound-settings': typeof SoundSettingsRoute
  '/tokens': typeof TokensRoute
  '/wireframes': typeof WireframesRoute
  '/devtools/finder-spec': typeof DevtoolsFinderSpecRoute
  '/edu-portal-admin/course-categories': typeof EduPortalAdminCourseCategoriesRoute
  '/edu-portal-admin/dashboard': typeof EduPortalAdminDashboardRoute
  '/edu-portal-admin/role-categories': typeof EduPortalAdminRoleCategoriesRoute
  '/edu-portal-admin/video-order': typeof EduPortalAdminVideoOrderRoute
  '/edu-portal-admin/videos': typeof EduPortalAdminVideosRouteWithChildren
  '/finder/$': typeof FinderSplatRoute
  '/genres/analytics': typeof GenresAnalyticsRoute
  '/genres/board': typeof GenresBoardRoute
  '/genres/chat': typeof GenresChatRoute
  '/genres/crm': typeof GenresCrmRoute
  '/genres/editor': typeof GenresEditorRoute
  '/genres/feed': typeof GenresFeedRoute
  '/genres/inbox': typeof GenresInboxRoute
  '/genres/settings': typeof GenresSettingsRoute
  '/genres/shop': typeof GenresShopRoute
  '/markdown/$': typeof MarkdownSplatRoute
  '/edu-portal-admin/': typeof EduPortalAdminIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/edu-portal-admin/videos/new': typeof EduPortalAdminVideosNewRoute
  '/m/finder/$': typeof MFinderSplatRoute
  '/edu-portal-admin/videos/': typeof EduPortalAdminVideosIndexRoute
  '/edu-portal-admin/videos/$id/edit': typeof EduPortalAdminVideosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas'
    | '/compositions'
    | '/content'
    | '/edu-portal-admin'
    | '/genres'
    | '/inspector'
    | '/keyboard'
    | '/sidebar-gallery'
    | '/sound-settings'
    | '/tokens'
    | '/wireframes'
    | '/devtools/finder-spec'
    | '/edu-portal-admin/course-categories'
    | '/edu-portal-admin/dashboard'
    | '/edu-portal-admin/role-categories'
    | '/edu-portal-admin/video-order'
    | '/edu-portal-admin/videos'
    | '/finder/$'
    | '/genres/analytics'
    | '/genres/board'
    | '/genres/chat'
    | '/genres/crm'
    | '/genres/editor'
    | '/genres/feed'
    | '/genres/inbox'
    | '/genres/settings'
    | '/genres/shop'
    | '/markdown/$'
    | '/edu-portal-admin/'
    | '/genres/'
    | '/edu-portal-admin/videos/new'
    | '/m/finder/$'
    | '/edu-portal-admin/videos/'
    | '/edu-portal-admin/videos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas'
    | '/compositions'
    | '/content'
    | '/inspector'
    | '/keyboard'
    | '/sidebar-gallery'
    | '/sound-settings'
    | '/tokens'
    | '/wireframes'
    | '/devtools/finder-spec'
    | '/edu-portal-admin/course-categories'
    | '/edu-portal-admin/dashboard'
    | '/edu-portal-admin/role-categories'
    | '/edu-portal-admin/video-order'
    | '/finder/$'
    | '/genres/analytics'
    | '/genres/board'
    | '/genres/chat'
    | '/genres/crm'
    | '/genres/editor'
    | '/genres/feed'
    | '/genres/inbox'
    | '/genres/settings'
    | '/genres/shop'
    | '/markdown/$'
    | '/edu-portal-admin'
    | '/genres'
    | '/edu-portal-admin/videos/new'
    | '/m/finder/$'
    | '/edu-portal-admin/videos'
    | '/edu-portal-admin/videos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/canvas'
    | '/compositions'
    | '/content'
    | '/edu-portal-admin'
    | '/genres'
    | '/inspector'
    | '/keyboard'
    | '/sidebar-gallery'
    | '/sound-settings'
    | '/tokens'
    | '/wireframes'
    | '/devtools/finder-spec'
    | '/edu-portal-admin/course-categories'
    | '/edu-portal-admin/dashboard'
    | '/edu-portal-admin/role-categories'
    | '/edu-portal-admin/video-order'
    | '/edu-portal-admin/videos'
    | '/finder/$'
    | '/genres/analytics'
    | '/genres/board'
    | '/genres/chat'
    | '/genres/crm'
    | '/genres/editor'
    | '/genres/feed'
    | '/genres/inbox'
    | '/genres/settings'
    | '/genres/shop'
    | '/markdown/$'
    | '/edu-portal-admin/'
    | '/genres/'
    | '/edu-portal-admin/videos/new'
    | '/m/finder/$'
    | '/edu-portal-admin/videos/'
    | '/edu-portal-admin/videos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanvasRoute: typeof CanvasRoute
  CompositionsRoute: typeof CompositionsRoute
  ContentRoute: typeof ContentRoute
  EduPortalAdminRoute: typeof EduPortalAdminRouteWithChildren
  GenresRoute: typeof GenresRouteWithChildren
  InspectorRoute: typeof InspectorRoute
  KeyboardRoute: typeof KeyboardRoute
  SidebarGalleryRoute: typeof SidebarGalleryRoute
  SoundSettingsRoute: typeof SoundSettingsRoute
  TokensRoute: typeof TokensRoute
  WireframesRoute: typeof WireframesRoute
  DevtoolsFinderSpecRoute: typeof DevtoolsFinderSpecRoute
  FinderSplatRoute: typeof FinderSplatRoute
  MarkdownSplatRoute: typeof MarkdownSplatRoute
  MFinderSplatRoute: typeof MFinderSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wireframes': {
      id: '/wireframes'
      path: '/wireframes'
      fullPath: '/wireframes'
      preLoaderRoute: typeof WireframesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-settings': {
      id: '/sound-settings'
      path: '/sound-settings'
      fullPath: '/sound-settings'
      preLoaderRoute: typeof SoundSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sidebar-gallery': {
      id: '/sidebar-gallery'
      path: '/sidebar-gallery'
      fullPath: '/sidebar-gallery'
      preLoaderRoute: typeof SidebarGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keyboard': {
      id: '/keyboard'
      path: '/keyboard'
      fullPath: '/keyboard'
      preLoaderRoute: typeof KeyboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspector': {
      id: '/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof InspectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-portal-admin': {
      id: '/edu-portal-admin'
      path: '/edu-portal-admin'
      fullPath: '/edu-portal-admin'
      preLoaderRoute: typeof EduPortalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compositions': {
      id: '/compositions'
      path: '/compositions'
      fullPath: '/compositions'
      preLoaderRoute: typeof CompositionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof GenresRoute
    }
    '/edu-portal-admin/': {
      id: '/edu-portal-admin/'
      path: '/'
      fullPath: '/edu-portal-admin/'
      preLoaderRoute: typeof EduPortalAdminIndexRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/markdown/$': {
      id: '/markdown/$'
      path: '/markdown/$'
      fullPath: '/markdown/$'
      preLoaderRoute: typeof MarkdownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/shop': {
      id: '/genres/shop'
      path: '/shop'
      fullPath: '/genres/shop'
      preLoaderRoute: typeof GenresShopRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/settings': {
      id: '/genres/settings'
      path: '/settings'
      fullPath: '/genres/settings'
      preLoaderRoute: typeof GenresSettingsRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/inbox': {
      id: '/genres/inbox'
      path: '/inbox'
      fullPath: '/genres/inbox'
      preLoaderRoute: typeof GenresInboxRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/feed': {
      id: '/genres/feed'
      path: '/feed'
      fullPath: '/genres/feed'
      preLoaderRoute: typeof GenresFeedRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/editor': {
      id: '/genres/editor'
      path: '/editor'
      fullPath: '/genres/editor'
      preLoaderRoute: typeof GenresEditorRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/crm': {
      id: '/genres/crm'
      path: '/crm'
      fullPath: '/genres/crm'
      preLoaderRoute: typeof GenresCrmRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/chat': {
      id: '/genres/chat'
      path: '/chat'
      fullPath: '/genres/chat'
      preLoaderRoute: typeof GenresChatRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/board': {
      id: '/genres/board'
      path: '/board'
      fullPath: '/genres/board'
      preLoaderRoute: typeof GenresBoardRouteImport
      parentRoute: typeof GenresRoute
    }
    '/genres/analytics': {
      id: '/genres/analytics'
      path: '/analytics'
      fullPath: '/genres/analytics'
      preLoaderRoute: typeof GenresAnalyticsRouteImport
      parentRoute: typeof GenresRoute
    }
    '/finder/$': {
      id: '/finder/$'
      path: '/finder/$'
      fullPath: '/finder/$'
      preLoaderRoute: typeof FinderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-portal-admin/videos': {
      id: '/edu-portal-admin/videos'
      path: '/videos'
      fullPath: '/edu-portal-admin/videos'
      preLoaderRoute: typeof EduPortalAdminVideosRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/video-order': {
      id: '/edu-portal-admin/video-order'
      path: '/video-order'
      fullPath: '/edu-portal-admin/video-order'
      preLoaderRoute: typeof EduPortalAdminVideoOrderRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/role-categories': {
      id: '/edu-portal-admin/role-categories'
      path: '/role-categories'
      fullPath: '/edu-portal-admin/role-categories'
      preLoaderRoute: typeof EduPortalAdminRoleCategoriesRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/dashboard': {
      id: '/edu-portal-admin/dashboard'
      path: '/dashboard'
      fullPath: '/edu-portal-admin/dashboard'
      preLoaderRoute: typeof EduPortalAdminDashboardRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/edu-portal-admin/course-categories': {
      id: '/edu-portal-admin/course-categories'
      path: '/course-categories'
      fullPath: '/edu-portal-admin/course-categories'
      preLoaderRoute: typeof EduPortalAdminCourseCategoriesRouteImport
      parentRoute: typeof EduPortalAdminRoute
    }
    '/devtools/finder-spec': {
      id: '/devtools/finder-spec'
      path: '/devtools/finder-spec'
      fullPath: '/devtools/finder-spec'
      preLoaderRoute: typeof DevtoolsFinderSpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-portal-admin/videos/': {
      id: '/edu-portal-admin/videos/'
      path: '/'
      fullPath: '/edu-portal-admin/videos/'
      preLoaderRoute: typeof EduPortalAdminVideosIndexRouteImport
      parentRoute: typeof EduPortalAdminVideosRoute
    }
    '/m/finder/$': {
      id: '/m/finder/$'
      path: '/m/finder/$'
      fullPath: '/m/finder/$'
      preLoaderRoute: typeof MFinderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edu-portal-admin/videos/new': {
      id: '/edu-portal-admin/videos/new'
      path: '/new'
      fullPath: '/edu-portal-admin/videos/new'
      preLoaderRoute: typeof EduPortalAdminVideosNewRouteImport
      parentRoute: typeof EduPortalAdminVideosRoute
    }
    '/edu-portal-admin/videos/$id/edit': {
      id: '/edu-portal-admin/videos/$id/edit'
      path: '/$id/edit'
      fullPath: '/edu-portal-admin/videos/$id/edit'
      preLoaderRoute: typeof EduPortalAdminVideosIdEditRouteImport
      parentRoute: typeof EduPortalAdminVideosRoute
    }
  }
}

interface EduPortalAdminVideosRouteChildren {
  EduPortalAdminVideosNewRoute: typeof EduPortalAdminVideosNewRoute
  EduPortalAdminVideosIndexRoute: typeof EduPortalAdminVideosIndexRoute
  EduPortalAdminVideosIdEditRoute: typeof EduPortalAdminVideosIdEditRoute
}

const EduPortalAdminVideosRouteChildren: EduPortalAdminVideosRouteChildren = {
  EduPortalAdminVideosNewRoute: EduPortalAdminVideosNewRoute,
  EduPortalAdminVideosIndexRoute: EduPortalAdminVideosIndexRoute,
  EduPortalAdminVideosIdEditRoute: EduPortalAdminVideosIdEditRoute,
}

const EduPortalAdminVideosRouteWithChildren =
  EduPortalAdminVideosRoute._addFileChildren(EduPortalAdminVideosRouteChildren)

interface EduPortalAdminRouteChildren {
  EduPortalAdminCourseCategoriesRoute: typeof EduPortalAdminCourseCategoriesRoute
  EduPortalAdminDashboardRoute: typeof EduPortalAdminDashboardRoute
  EduPortalAdminRoleCategoriesRoute: typeof EduPortalAdminRoleCategoriesRoute
  EduPortalAdminVideoOrderRoute: typeof EduPortalAdminVideoOrderRoute
  EduPortalAdminVideosRoute: typeof EduPortalAdminVideosRouteWithChildren
  EduPortalAdminIndexRoute: typeof EduPortalAdminIndexRoute
}

const EduPortalAdminRouteChildren: EduPortalAdminRouteChildren = {
  EduPortalAdminCourseCategoriesRoute: EduPortalAdminCourseCategoriesRoute,
  EduPortalAdminDashboardRoute: EduPortalAdminDashboardRoute,
  EduPortalAdminRoleCategoriesRoute: EduPortalAdminRoleCategoriesRoute,
  EduPortalAdminVideoOrderRoute: EduPortalAdminVideoOrderRoute,
  EduPortalAdminVideosRoute: EduPortalAdminVideosRouteWithChildren,
  EduPortalAdminIndexRoute: EduPortalAdminIndexRoute,
}

const EduPortalAdminRouteWithChildren = EduPortalAdminRoute._addFileChildren(
  EduPortalAdminRouteChildren,
)

interface GenresRouteChildren {
  GenresAnalyticsRoute: typeof GenresAnalyticsRoute
  GenresBoardRoute: typeof GenresBoardRoute
  GenresChatRoute: typeof GenresChatRoute
  GenresCrmRoute: typeof GenresCrmRoute
  GenresEditorRoute: typeof GenresEditorRoute
  GenresFeedRoute: typeof GenresFeedRoute
  GenresInboxRoute: typeof GenresInboxRoute
  GenresSettingsRoute: typeof GenresSettingsRoute
  GenresShopRoute: typeof GenresShopRoute
  GenresIndexRoute: typeof GenresIndexRoute
}

const GenresRouteChildren: GenresRouteChildren = {
  GenresAnalyticsRoute: GenresAnalyticsRoute,
  GenresBoardRoute: GenresBoardRoute,
  GenresChatRoute: GenresChatRoute,
  GenresCrmRoute: GenresCrmRoute,
  GenresEditorRoute: GenresEditorRoute,
  GenresFeedRoute: GenresFeedRoute,
  GenresInboxRoute: GenresInboxRoute,
  GenresSettingsRoute: GenresSettingsRoute,
  GenresShopRoute: GenresShopRoute,
  GenresIndexRoute: GenresIndexRoute,
}

const GenresRouteWithChildren =
  GenresRoute._addFileChildren(GenresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanvasRoute: CanvasRoute,
  CompositionsRoute: CompositionsRoute,
  ContentRoute: ContentRoute,
  EduPortalAdminRoute: EduPortalAdminRouteWithChildren,
  GenresRoute: GenresRouteWithChildren,
  InspectorRoute: InspectorRoute,
  KeyboardRoute: KeyboardRoute,
  SidebarGalleryRoute: SidebarGalleryRoute,
  SoundSettingsRoute: SoundSettingsRoute,
  TokensRoute: TokensRoute,
  WireframesRoute: WireframesRoute,
  DevtoolsFinderSpecRoute: DevtoolsFinderSpecRoute,
  FinderSplatRoute: FinderSplatRoute,
  MarkdownSplatRoute: MarkdownSplatRoute,
  MFinderSplatRoute: MFinderSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
