import {
  alertPattern,
  alertdialogPattern,
  disclosurePattern,
  navigationListPattern,
  sliderPattern,
  splitterPattern,
  toggleSwitchPattern,
  useAccordionPattern,
  useComboboxPattern,
  useDialogPattern,
  useListboxPattern,
  useMenuPattern,
  useMenubarPattern,
  useRadioGroupPattern,
  useTabsPattern,
  useToolbarPattern,
  useTooltipPattern,
  useTreeGridPattern,
  useTreePattern,
} from './dist/patterns/index.js'
import { useRovingTabIndex, useSpatialNavigation, multiSelect, numericStep, selectionFollowsFocus } from './dist/index.js'
console.log('imports OK', {
  alertPattern: typeof alertPattern,
  alertdialogPattern: typeof alertdialogPattern,
  disclosurePattern: typeof disclosurePattern,
  navigationListPattern: typeof navigationListPattern,
  sliderPattern: typeof sliderPattern,
  splitterPattern: typeof splitterPattern,
  toggleSwitchPattern: typeof toggleSwitchPattern,
  useAccordionPattern: typeof useAccordionPattern,
  useComboboxPattern: typeof useComboboxPattern,
  useDialogPattern: typeof useDialogPattern,
  useListboxPattern: typeof useListboxPattern,
  useMenuPattern: typeof useMenuPattern,
  useMenubarPattern: typeof useMenubarPattern,
  useRadioGroupPattern: typeof useRadioGroupPattern,
  useTabsPattern: typeof useTabsPattern,
  useToolbarPattern: typeof useToolbarPattern,
  useTooltipPattern: typeof useTooltipPattern,
  useTreeGridPattern: typeof useTreeGridPattern,
  useTreePattern: typeof useTreePattern,
  multiSelect: typeof multiSelect,
  numericStep: typeof numericStep,
  selectionFollowsFocus: typeof selectionFollowsFocus,
  useRovingTabIndex: typeof useRovingTabIndex,
  useSpatialNavigation: typeof useSpatialNavigation,
})
