/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsAdminRouteImport } from './routes/apps.admin'
import { Route as AppsAdminIndexRouteImport } from './routes/apps.admin.index'
import { Route as AppsSlidesSplatRouteImport } from './routes/apps.slides.$'
import { Route as AppsMarkdownSplatRouteImport } from './routes/apps.markdown.$'
import { Route as AppsFinderSplatRouteImport } from './routes/apps.finder.$'
import { Route as AppsAdminVideosRouteImport } from './routes/apps.admin.videos'
import { Route as AppsAdminVideoOrderRouteImport } from './routes/apps.admin.video-order'
import { Route as AppsAdminRoleCategoriesRouteImport } from './routes/apps.admin.role-categories'
import { Route as AppsAdminDashboardRouteImport } from './routes/apps.admin.dashboard'
import { Route as AppsAdminCourseCategoriesRouteImport } from './routes/apps.admin.course-categories'
import { Route as AppsAdminVideosIndexRouteImport } from './routes/apps.admin.videos.index'
import { Route as AppsAdminVideosNewRouteImport } from './routes/apps.admin.videos.new'
import { Route as AppsAdminVideosIdEditRouteImport } from './routes/apps.admin.videos.$id.edit'

const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAdminRoute = AppsAdminRouteImport.update({
  id: '/apps/admin',
  path: '/apps/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAdminIndexRoute = AppsAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsAdminRoute,
} as any)
const AppsSlidesSplatRoute = AppsSlidesSplatRouteImport.update({
  id: '/apps/slides/$',
  path: '/apps/slides/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsMarkdownSplatRoute = AppsMarkdownSplatRouteImport.update({
  id: '/apps/markdown/$',
  path: '/apps/markdown/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsFinderSplatRoute = AppsFinderSplatRouteImport.update({
  id: '/apps/finder/$',
  path: '/apps/finder/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsAdminVideosRoute = AppsAdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AppsAdminRoute,
} as any)
const AppsAdminVideoOrderRoute = AppsAdminVideoOrderRouteImport.update({
  id: '/video-order',
  path: '/video-order',
  getParentRoute: () => AppsAdminRoute,
} as any)
const AppsAdminRoleCategoriesRoute = AppsAdminRoleCategoriesRouteImport.update({
  id: '/role-categories',
  path: '/role-categories',
  getParentRoute: () => AppsAdminRoute,
} as any)
const AppsAdminDashboardRoute = AppsAdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppsAdminRoute,
} as any)
const AppsAdminCourseCategoriesRoute =
  AppsAdminCourseCategoriesRouteImport.update({
    id: '/course-categories',
    path: '/course-categories',
    getParentRoute: () => AppsAdminRoute,
  } as any)
const AppsAdminVideosIndexRoute = AppsAdminVideosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppsAdminVideosRoute,
} as any)
const AppsAdminVideosNewRoute = AppsAdminVideosNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppsAdminVideosRoute,
} as any)
const AppsAdminVideosIdEditRoute = AppsAdminVideosIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => AppsAdminVideosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/apps/admin': typeof AppsAdminRouteWithChildren
  '/apps/admin/course-categories': typeof AppsAdminCourseCategoriesRoute
  '/apps/admin/dashboard': typeof AppsAdminDashboardRoute
  '/apps/admin/role-categories': typeof AppsAdminRoleCategoriesRoute
  '/apps/admin/video-order': typeof AppsAdminVideoOrderRoute
  '/apps/admin/videos': typeof AppsAdminVideosRouteWithChildren
  '/apps/finder/$': typeof AppsFinderSplatRoute
  '/apps/markdown/$': typeof AppsMarkdownSplatRoute
  '/apps/slides/$': typeof AppsSlidesSplatRoute
  '/apps/admin/': typeof AppsAdminIndexRoute
  '/apps/admin/videos/new': typeof AppsAdminVideosNewRoute
  '/apps/admin/videos/': typeof AppsAdminVideosIndexRoute
  '/apps/admin/videos/$id/edit': typeof AppsAdminVideosIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/apps/admin/course-categories': typeof AppsAdminCourseCategoriesRoute
  '/apps/admin/dashboard': typeof AppsAdminDashboardRoute
  '/apps/admin/role-categories': typeof AppsAdminRoleCategoriesRoute
  '/apps/admin/video-order': typeof AppsAdminVideoOrderRoute
  '/apps/finder/$': typeof AppsFinderSplatRoute
  '/apps/markdown/$': typeof AppsMarkdownSplatRoute
  '/apps/slides/$': typeof AppsSlidesSplatRoute
  '/apps/admin': typeof AppsAdminIndexRoute
  '/apps/admin/videos/new': typeof AppsAdminVideosNewRoute
  '/apps/admin/videos': typeof AppsAdminVideosIndexRoute
  '/apps/admin/videos/$id/edit': typeof AppsAdminVideosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/patterns': typeof PatternsRoute
  '/apps/admin': typeof AppsAdminRouteWithChildren
  '/apps/admin/course-categories': typeof AppsAdminCourseCategoriesRoute
  '/apps/admin/dashboard': typeof AppsAdminDashboardRoute
  '/apps/admin/role-categories': typeof AppsAdminRoleCategoriesRoute
  '/apps/admin/video-order': typeof AppsAdminVideoOrderRoute
  '/apps/admin/videos': typeof AppsAdminVideosRouteWithChildren
  '/apps/finder/$': typeof AppsFinderSplatRoute
  '/apps/markdown/$': typeof AppsMarkdownSplatRoute
  '/apps/slides/$': typeof AppsSlidesSplatRoute
  '/apps/admin/': typeof AppsAdminIndexRoute
  '/apps/admin/videos/new': typeof AppsAdminVideosNewRoute
  '/apps/admin/videos/': typeof AppsAdminVideosIndexRoute
  '/apps/admin/videos/$id/edit': typeof AppsAdminVideosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/patterns'
    | '/apps/admin'
    | '/apps/admin/course-categories'
    | '/apps/admin/dashboard'
    | '/apps/admin/role-categories'
    | '/apps/admin/video-order'
    | '/apps/admin/videos'
    | '/apps/finder/$'
    | '/apps/markdown/$'
    | '/apps/slides/$'
    | '/apps/admin/'
    | '/apps/admin/videos/new'
    | '/apps/admin/videos/'
    | '/apps/admin/videos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/patterns'
    | '/apps/admin/course-categories'
    | '/apps/admin/dashboard'
    | '/apps/admin/role-categories'
    | '/apps/admin/video-order'
    | '/apps/finder/$'
    | '/apps/markdown/$'
    | '/apps/slides/$'
    | '/apps/admin'
    | '/apps/admin/videos/new'
    | '/apps/admin/videos'
    | '/apps/admin/videos/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/patterns'
    | '/apps/admin'
    | '/apps/admin/course-categories'
    | '/apps/admin/dashboard'
    | '/apps/admin/role-categories'
    | '/apps/admin/video-order'
    | '/apps/admin/videos'
    | '/apps/finder/$'
    | '/apps/markdown/$'
    | '/apps/slides/$'
    | '/apps/admin/'
    | '/apps/admin/videos/new'
    | '/apps/admin/videos/'
    | '/apps/admin/videos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PatternsRoute: typeof PatternsRoute
  AppsAdminRoute: typeof AppsAdminRouteWithChildren
  AppsFinderSplatRoute: typeof AppsFinderSplatRoute
  AppsMarkdownSplatRoute: typeof AppsMarkdownSplatRoute
  AppsSlidesSplatRoute: typeof AppsSlidesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/admin': {
      id: '/apps/admin'
      path: '/apps/admin'
      fullPath: '/apps/admin'
      preLoaderRoute: typeof AppsAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/admin/': {
      id: '/apps/admin/'
      path: '/'
      fullPath: '/apps/admin/'
      preLoaderRoute: typeof AppsAdminIndexRouteImport
      parentRoute: typeof AppsAdminRoute
    }
    '/apps/slides/$': {
      id: '/apps/slides/$'
      path: '/apps/slides/$'
      fullPath: '/apps/slides/$'
      preLoaderRoute: typeof AppsSlidesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/markdown/$': {
      id: '/apps/markdown/$'
      path: '/apps/markdown/$'
      fullPath: '/apps/markdown/$'
      preLoaderRoute: typeof AppsMarkdownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/finder/$': {
      id: '/apps/finder/$'
      path: '/apps/finder/$'
      fullPath: '/apps/finder/$'
      preLoaderRoute: typeof AppsFinderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/admin/videos': {
      id: '/apps/admin/videos'
      path: '/videos'
      fullPath: '/apps/admin/videos'
      preLoaderRoute: typeof AppsAdminVideosRouteImport
      parentRoute: typeof AppsAdminRoute
    }
    '/apps/admin/video-order': {
      id: '/apps/admin/video-order'
      path: '/video-order'
      fullPath: '/apps/admin/video-order'
      preLoaderRoute: typeof AppsAdminVideoOrderRouteImport
      parentRoute: typeof AppsAdminRoute
    }
    '/apps/admin/role-categories': {
      id: '/apps/admin/role-categories'
      path: '/role-categories'
      fullPath: '/apps/admin/role-categories'
      preLoaderRoute: typeof AppsAdminRoleCategoriesRouteImport
      parentRoute: typeof AppsAdminRoute
    }
    '/apps/admin/dashboard': {
      id: '/apps/admin/dashboard'
      path: '/dashboard'
      fullPath: '/apps/admin/dashboard'
      preLoaderRoute: typeof AppsAdminDashboardRouteImport
      parentRoute: typeof AppsAdminRoute
    }
    '/apps/admin/course-categories': {
      id: '/apps/admin/course-categories'
      path: '/course-categories'
      fullPath: '/apps/admin/course-categories'
      preLoaderRoute: typeof AppsAdminCourseCategoriesRouteImport
      parentRoute: typeof AppsAdminRoute
    }
    '/apps/admin/videos/': {
      id: '/apps/admin/videos/'
      path: '/'
      fullPath: '/apps/admin/videos/'
      preLoaderRoute: typeof AppsAdminVideosIndexRouteImport
      parentRoute: typeof AppsAdminVideosRoute
    }
    '/apps/admin/videos/new': {
      id: '/apps/admin/videos/new'
      path: '/new'
      fullPath: '/apps/admin/videos/new'
      preLoaderRoute: typeof AppsAdminVideosNewRouteImport
      parentRoute: typeof AppsAdminVideosRoute
    }
    '/apps/admin/videos/$id/edit': {
      id: '/apps/admin/videos/$id/edit'
      path: '/$id/edit'
      fullPath: '/apps/admin/videos/$id/edit'
      preLoaderRoute: typeof AppsAdminVideosIdEditRouteImport
      parentRoute: typeof AppsAdminVideosRoute
    }
  }
}

interface AppsAdminVideosRouteChildren {
  AppsAdminVideosNewRoute: typeof AppsAdminVideosNewRoute
  AppsAdminVideosIndexRoute: typeof AppsAdminVideosIndexRoute
  AppsAdminVideosIdEditRoute: typeof AppsAdminVideosIdEditRoute
}

const AppsAdminVideosRouteChildren: AppsAdminVideosRouteChildren = {
  AppsAdminVideosNewRoute: AppsAdminVideosNewRoute,
  AppsAdminVideosIndexRoute: AppsAdminVideosIndexRoute,
  AppsAdminVideosIdEditRoute: AppsAdminVideosIdEditRoute,
}

const AppsAdminVideosRouteWithChildren = AppsAdminVideosRoute._addFileChildren(
  AppsAdminVideosRouteChildren,
)

interface AppsAdminRouteChildren {
  AppsAdminCourseCategoriesRoute: typeof AppsAdminCourseCategoriesRoute
  AppsAdminDashboardRoute: typeof AppsAdminDashboardRoute
  AppsAdminRoleCategoriesRoute: typeof AppsAdminRoleCategoriesRoute
  AppsAdminVideoOrderRoute: typeof AppsAdminVideoOrderRoute
  AppsAdminVideosRoute: typeof AppsAdminVideosRouteWithChildren
  AppsAdminIndexRoute: typeof AppsAdminIndexRoute
}

const AppsAdminRouteChildren: AppsAdminRouteChildren = {
  AppsAdminCourseCategoriesRoute: AppsAdminCourseCategoriesRoute,
  AppsAdminDashboardRoute: AppsAdminDashboardRoute,
  AppsAdminRoleCategoriesRoute: AppsAdminRoleCategoriesRoute,
  AppsAdminVideoOrderRoute: AppsAdminVideoOrderRoute,
  AppsAdminVideosRoute: AppsAdminVideosRouteWithChildren,
  AppsAdminIndexRoute: AppsAdminIndexRoute,
}

const AppsAdminRouteWithChildren = AppsAdminRoute._addFileChildren(
  AppsAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PatternsRoute: PatternsRoute,
  AppsAdminRoute: AppsAdminRouteWithChildren,
  AppsFinderSplatRoute: AppsFinderSplatRoute,
  AppsMarkdownSplatRoute: AppsMarkdownSplatRoute,
  AppsSlidesSplatRoute: AppsSlidesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
