/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrappersRouteImport } from './routes/wrappers'
import { Route as PatternsRouteImport } from './routes/patterns'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as DataRouteImport } from './routes/data'
import { Route as AxesRouteImport } from './routes/axes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppsSlidesSplatRouteImport } from './routes/apps.slides.$'
import { Route as AppsMarkdownSplatRouteImport } from './routes/apps.markdown.$'
import { Route as AppsFinderSplatRouteImport } from './routes/apps.finder.$'

const WrappersRoute = WrappersRouteImport.update({
  id: '/wrappers',
  path: '/wrappers',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternsRoute = PatternsRouteImport.update({
  id: '/patterns',
  path: '/patterns',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const AxesRoute = AxesRouteImport.update({
  id: '/axes',
  path: '/axes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlidesSplatRoute = AppsSlidesSplatRouteImport.update({
  id: '/apps/slides/$',
  path: '/apps/slides/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsMarkdownSplatRoute = AppsMarkdownSplatRouteImport.update({
  id: '/apps/markdown/$',
  path: '/apps/markdown/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsFinderSplatRoute = AppsFinderSplatRouteImport.update({
  id: '/apps/finder/$',
  path: '/apps/finder/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/axes': typeof AxesRoute
  '/data': typeof DataRoute
  '/matrix': typeof MatrixRoute
  '/patterns': typeof PatternsRoute
  '/wrappers': typeof WrappersRoute
  '/apps/finder/$': typeof AppsFinderSplatRoute
  '/apps/markdown/$': typeof AppsMarkdownSplatRoute
  '/apps/slides/$': typeof AppsSlidesSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/axes': typeof AxesRoute
  '/data': typeof DataRoute
  '/matrix': typeof MatrixRoute
  '/patterns': typeof PatternsRoute
  '/wrappers': typeof WrappersRoute
  '/apps/finder/$': typeof AppsFinderSplatRoute
  '/apps/markdown/$': typeof AppsMarkdownSplatRoute
  '/apps/slides/$': typeof AppsSlidesSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/axes': typeof AxesRoute
  '/data': typeof DataRoute
  '/matrix': typeof MatrixRoute
  '/patterns': typeof PatternsRoute
  '/wrappers': typeof WrappersRoute
  '/apps/finder/$': typeof AppsFinderSplatRoute
  '/apps/markdown/$': typeof AppsMarkdownSplatRoute
  '/apps/slides/$': typeof AppsSlidesSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/axes'
    | '/data'
    | '/matrix'
    | '/patterns'
    | '/wrappers'
    | '/apps/finder/$'
    | '/apps/markdown/$'
    | '/apps/slides/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/axes'
    | '/data'
    | '/matrix'
    | '/patterns'
    | '/wrappers'
    | '/apps/finder/$'
    | '/apps/markdown/$'
    | '/apps/slides/$'
  id:
    | '__root__'
    | '/'
    | '/axes'
    | '/data'
    | '/matrix'
    | '/patterns'
    | '/wrappers'
    | '/apps/finder/$'
    | '/apps/markdown/$'
    | '/apps/slides/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AxesRoute: typeof AxesRoute
  DataRoute: typeof DataRoute
  MatrixRoute: typeof MatrixRoute
  PatternsRoute: typeof PatternsRoute
  WrappersRoute: typeof WrappersRoute
  AppsFinderSplatRoute: typeof AppsFinderSplatRoute
  AppsMarkdownSplatRoute: typeof AppsMarkdownSplatRoute
  AppsSlidesSplatRoute: typeof AppsSlidesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrappers': {
      id: '/wrappers'
      path: '/wrappers'
      fullPath: '/wrappers'
      preLoaderRoute: typeof WrappersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patterns': {
      id: '/patterns'
      path: '/patterns'
      fullPath: '/patterns'
      preLoaderRoute: typeof PatternsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/axes': {
      id: '/axes'
      path: '/axes'
      fullPath: '/axes'
      preLoaderRoute: typeof AxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/slides/$': {
      id: '/apps/slides/$'
      path: '/apps/slides/$'
      fullPath: '/apps/slides/$'
      preLoaderRoute: typeof AppsSlidesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/markdown/$': {
      id: '/apps/markdown/$'
      path: '/apps/markdown/$'
      fullPath: '/apps/markdown/$'
      preLoaderRoute: typeof AppsMarkdownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/finder/$': {
      id: '/apps/finder/$'
      path: '/apps/finder/$'
      fullPath: '/apps/finder/$'
      preLoaderRoute: typeof AppsFinderSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AxesRoute: AxesRoute,
  DataRoute: DataRoute,
  MatrixRoute: MatrixRoute,
  PatternsRoute: PatternsRoute,
  WrappersRoute: WrappersRoute,
  AppsFinderSplatRoute: AppsFinderSplatRoute,
  AppsMarkdownSplatRoute: AppsMarkdownSplatRoute,
  AppsSlidesSplatRoute: AppsSlidesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
