export { EduPortalAdmin } from './widgets/EduPortalAdmin'
export { Sidebar } from './widgets/Sidebar'
export { Topbar } from './widgets/Topbar'

export { Dashboard } from './pages/Dashboard'
export { VideoList } from './pages/VideoList'
export { VideoEdit } from './pages/VideoEdit'
export { CourseCategory } from './pages/CourseCategory'
export { RoleCategory } from './pages/RoleCategory'
export { VideoOrder } from './pages/VideoOrder'
