export { Slides } from './widgets/Slides'
export { splitMarkdown } from './features/split'
export type { Slide, Deck } from './entities/schema'
export { slidesCss } from './style'
export { default } from './plugin'
